### ISSUE TITLE
Make CRAM default alignment format

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/exoseq#14]
Include the `--bam` switch and make CRAM the default output for BWA and ApplyBQSR

**Comment by MaxUlysse** [comment]
I'm all for the new stuff, but as CRAM is the newest format, shouldn't BAM be the default output format and CRAM the optional?
Aren't we loosing some quality information at some point with enforcing CRAM?

**Comment by marchoeppner** [comment]
Lossless CRAM should be fine; I am more thinking of the "educational" aspect. We are really trying to push CRAM since the information content is equivalent, but storage requirements reduced by about 40%. For sequencing centers in particular (but any bfx user, really), this is quite significant. If you make CRAM the optional format, noone will use it
