### ISSUE TITLE
Move FastQC into trimGalore

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/exoseq#15]
Move the fastqc analysis into trimgalore using the built-in `--fastqc` option. This way we get metrics about the actually used data rather than the initial raw data (which sequencing centers usually include anyway)

**Comment by ewels** [comment]
NB: If I ever get around to it, I hope to add a feature to group certain samples (especially FastQC) for read pairs and pre/post-trimming.

Code is mostly already written (see https://github.com/ewels/MultiQC/pull/576 and https://github.com/ewels/MultiQC/issues/542), just need to get around to finishing it up and testing it.

**Comment by apeltzer** [comment]
Resolved :-)
