### ISSUE TITLE
Move kits to a base params definition, similar to igenomes 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/exoseq#7]
Maybe with download option :-)

**Comment by ewels** [comment]
Or perhaps _into_ iGenomes.. (rename to `nf-core/references`?)

**Comment by apeltzer** [comment]
The question there would be whether we are allowed to do that? Is there a limitation e.g. by Agilent?

**Comment by apeltzer** [comment]
Kit files are not yet part - iGenomes stuff can be used for stuff... However, `--kitfiles` works for specifying where your kit files are....
